name: nlp
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - numpy
  - torch
  - pytorch-cuda=11.6
  - seaborn
  - matplotlib
  - pandas
  - scikit-learn
  - tqdm
  - jupyter
  - jupyterlab
  - pip
  - pip:
      - transformers
      - nltk