name: nlp-tweets
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - pandas
  - matplotlib
  - numpy
  - seaborn
  - pytorch-cuda=11.6
  - pytorch
  - ld_impl_linux-64
  - readline
  - python-dateutil
  - xz
  - ptyprocess
  - libsodium
  - entrypoints
  - ncurses
  - asttokens
  - pygments
  - libgcc-ng
  - libgomp
  - prompt-toolkit
  - ipython
  - pyparsing
  - pickleshare
  - pyzmq
  - jedi
  - pexpect
  - pure_eval
  - executing
  - setuptools
  - certifi
  - parso
  - stack_data
  - packaging
  - tk
  - jupyter_core
  - _openmp_mutex
  - wcwidth
  - six
  - sqlite
  - ca-certificates
  - matplotlib-inline
  - zlib
  - backcall
  - libstdcxx-ng
  - wheel
  - _libgcc_mutex
  - decorator
  - nest-asyncio
  - jupyter_client
  - tornado
  - debugpy
  - libffi
  - libuuid
  - traitlets
  - tzdata
  - psutil
  - zeromq
  - bzip2
  - openssl
  - pip
  - ipykernel
