name: nlp-tweets
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter
  - pandas
  - matplotlib
  - numpy
  - seaborn
  - pytorch 
  - pytorch-cuda=11.6
  - sklearn
  - tqdm
